name: shop_savvy_delivery
description: ShopSavvy delivery application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  lottie: ^2.4.0
  firebase_messaging: ^14.6.4
  firebase_core: ^2.14.0
  flutter_local_notifications: ^15.0.1
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  google_sign_in: ^6.1.4
  responsive_builder: ^0.7.0
  flutter_otp_text_field: ^1.1.1
  cached_network_image: ^3.2.3
  http: ^1.1.0
  marquee: ^2.2.3
  google_maps_flutter: ^2.3.1
  geolocator: ^9.0.2
  flutter_ringtone_player: ^3.2.0
  jiffy: ^6.2.1
  url_launcher: ^6.1.11
  rating_dialog: ^2.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/flags/
    - assets/lottie/
    - assets/fonts/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - weight: 700

    - family: PlayFairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
        - weight: 700

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
        - weight: 700
