// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBas3ccWpdGVh4RImTsvVFsa8cNj7BQhDs',
    appId: '1:425612938966:web:2f9b0eafe840db00708377',
    messagingSenderId: '425612938966',
    projectId: 'shopsavvy-delivery',
    authDomain: 'shopsavvy-delivery.firebaseapp.com',
    storageBucket: 'shopsavvy-delivery.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAypSqbFwBNzTqkWBbxYVgkKiukbI7Ry4g',
    appId: '1:425612938966:android:41c9cc05d99cdea8708377',
    messagingSenderId: '425612938966',
    projectId: 'shopsavvy-delivery',
    storageBucket: 'shopsavvy-delivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0BfdP5k58_xf8fWmnAVNXy5lTQbm1pxo',
    appId: '1:425612938966:ios:69b59c97e37af7c0708377',
    messagingSenderId: '425612938966',
    projectId: 'shopsavvy-delivery',
    storageBucket: 'shopsavvy-delivery.appspot.com',
    iosClientId: '425612938966-baa15l3pv1un2af7vno3jijd3di6u2ml.apps.googleusercontent.com',
    iosBundleId: 'com.IBMF.shopSavvyDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0BfdP5k58_xf8fWmnAVNXy5lTQbm1pxo',
    appId: '1:425612938966:ios:feaf08b3cef7c594708377',
    messagingSenderId: '425612938966',
    projectId: 'shopsavvy-delivery',
    storageBucket: 'shopsavvy-delivery.appspot.com',
    iosClientId: '425612938966-9mngu82mt52smp45htf0ef0j7ml2q19p.apps.googleusercontent.com',
    iosBundleId: 'com.IBMF.shopSavvyDelivery.RunnerTests',
  );
}
